### ISSUE TITLE
ModuleNotFoundError: No module named 'iqflow.env'

### ISSUE THREAD

**Issue by dbleyl** [data-and-decision-lab/IQ-Flow#1]
Following the instructions,

```bash
> iqflow/trainer python train_multiprocess.py --alg qflow --exp ssd --n_seeds 5 --config config_ssd_qflow
```
Results in:

```bash
Traceback (most recent call last):
  File "train_multiprocess.py", line 48, in <module>
    import single_trainer_ssd as train_ssd
  File "/opt/code/repos/IQ-Flow/iqflow/trainer/single_trainer_ssd.py", line 4, in <module>
    import iqflow.env.ssd.ssd as ssd
ModuleNotFoundError: No module named 'iqflow.env'
```

**Comment by AbdullahVanlioglu** [comment]
env folder added
